import type { FbGroup, Post } from "./types";

export const SEED_GROUPS: FbGroup[] = [
  {
    id: "g1",
    name: "Houses for Rent in Colombo & Suburbs",
    url: "https://www.facebook.com/groups/housesforrentcolombo",
    addedAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "g2",
    name: "Malabe / Kaduwela Rentals",
    url: "https://www.facebook.com/groups/malaberentals",
    addedAt: "2026-06-02T10:00:00Z",
  },
  {
    id: "g3",
    name: "Annex & Rooms Sri Lanka",
    url: "https://www.facebook.com/groups/annexsrilanka",
    addedAt: "2026-06-05T10:00:00Z",
  },
];

export const SUGGESTED_LOCATIONS = [
  "Malabe",
  "Kaduwela",
  "Battaramulla",
  "Athurugiriya",
  "Kothalawala",
  "Thalahena",
  "Pelawatte",
  "Rajagiriya",
  "Kotte",
  "Nugegoda",
];

export const SUGGESTED_KEYWORDS = [
  "annex",
  "annexe",
  "house",
  "apartment",
  "2 rooms",
  "two rooms",
  "2 bedroom",
  "kitchen",
  "attached bathroom",
  "parking",
  "furnished",
  "unfurnished",
];

export const SEED_POSTS: Post[] = [
  {
    id: "p1",
    groupId: "g2",
    groupName: "Malabe / Kaduwela Rentals",
    author: "Nimal Perera",
    text: "Annex for rent in Malabe, close to SLIIT. 2 rooms, kitchen, attached bathroom, parking for 1 vehicle. Rent: 45,000/= per month. Contact for viewing.",
    permalink: "https://www.facebook.com/groups/malaberentals/posts/100001",
    postedAt: "2026-06-22T08:15:00Z",
    priceLkr: 45000,
  },
  {
    id: "p2",
    groupId: "g1",
    groupName: "Houses for Rent in Colombo & Suburbs",
    author: "Anjali Silva",
    text: "House for rent in Battaramulla. 3 bedrooms, large kitchen, parking for 2 vehicles. Fully furnished. 120,000 per month.",
    permalink: "https://www.facebook.com/groups/housesforrentcolombo/posts/100002",
    postedAt: "2026-06-22T11:40:00Z",
    priceLkr: 120000,
  },
  {
    id: "p3",
    groupId: "g3",
    groupName: "Annex & Rooms Sri Lanka",
    author: "Saman Fernando",
    text: "Newly built annexe in Kaduwela. Two rooms with kitchen and pantry. Unfurnished. 38,000/= monthly. Walking distance to bus halt.",
    permalink: "https://www.facebook.com/groups/annexsrilanka/posts/100003",
    postedAt: "2026-06-21T19:05:00Z",
    priceLkr: 38000,
  },
  {
    id: "p4",
    groupId: "g2",
    groupName: "Malabe / Kaduwela Rentals",
    author: "Dilshan R.",
    text: "Single room available in Malabe Pelawatte side. Shared kitchen. Suitable for working professional or student. 18,000/=.",
    permalink: "https://www.facebook.com/groups/malaberentals/posts/100004",
    postedAt: "2026-06-23T07:30:00Z",
    priceLkr: 18000,
  },
  {
    id: "p5",
    groupId: "g1",
    groupName: "Houses for Rent in Colombo & Suburbs",
    author: "Property Lk",
    text: "Apartment for rent Rajagiriya, 2 bedroom, kitchen, fully furnished. Reserved parking. 85,000.",
    permalink: "https://www.facebook.com/groups/housesforrentcolombo/posts/100005",
    postedAt: "2026-06-20T14:00:00Z",
    priceLkr: 85000,
  },
  {
    id: "p6",
    groupId: "g3",
    groupName: "Annex & Rooms Sri Lanka",
    author: "Kumari W.",
    text: "Annex Athurugiriya - 2 rooms, kitchen, attached bathroom, separate entrance, parking. 42,000 per month.",
    permalink: "https://www.facebook.com/groups/annexsrilanka/posts/100006",
    postedAt: "2026-06-23T09:45:00Z",
    priceLkr: 42000,
  },
  {
    id: "p7",
    groupId: "g2",
    groupName: "Malabe / Kaduwela Rentals",
    author: "Ravi P.",
    text: "Looking for an annex Malabe area. 2 rooms with kitchen preferred. Budget around 50k. Please WhatsApp.",
    permalink: "https://www.facebook.com/groups/malaberentals/posts/100007",
    postedAt: "2026-06-23T10:10:00Z",
  },
  {
    id: "p8",
    groupId: "g1",
    groupName: "Houses for Rent in Colombo & Suburbs",
    author: "Estate Agent",
    text: "Office space available Nugegoda. 1500 sq ft. Parking for 4. Long-term lease preferred.",
    permalink: "https://www.facebook.com/groups/housesforrentcolombo/posts/100008",
    postedAt: "2026-06-19T16:20:00Z",
  },
];
